# Generated by Django 4.1.7 on 2024-05-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0003_rename_categories_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
