# Generated by Django 4.1.7 on 2024-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0005_alter_category_name_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
