# Generated by Django 4.1.7 on 2024-05-14 02:01

from django.db import migrations, models
import tastopia.models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='photo',
            field=models.ImageField(upload_to=tastopia.models.recipeDirectoryPath),
        ),
    ]
