# Generated by Django 4.1.7 on 2024-05-14 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0007_remove_user_age_user_date_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tastopia.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UploadedRecipe',
        ),
    ]
