# Generated by Django 4.1.7 on 2024-05-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0007_recipe_duration_alter_recipephoto_photo'),
        ('tastopia', '0008_recipe_user_delete_uploadedrecipe'),
    ]

    operations = [
    ]
