# Generated by Django 4.1.7 on 2024-05-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0009_merge_20240513_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
