# Generated by Django 4.1.7 on 2024-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0010_recipe_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='valoration',
            field=models.IntegerField(default=0),
        ),
    ]
