# Generated by Django 4.1.7 on 2024-05-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0011_alter_recipe_valoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
