# Generated by Django 4.1.7 on 2024-05-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0012_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
