# Generated by Django 4.1.7 on 2024-05-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0012_remove_recipe_user'),
        ('tastopia', '0013_remove_customuser_first_name_and_more'),
    ]

    operations = [
    ]
