# Generated by Django 4.1.7 on 2024-05-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0014_merge_20240519_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tastopia.customuser'),
            preserve_default=False,
        ),
    ]
