# Generated by Django 4.1.7 on 2024-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0014_merge_20240519_0027'),
        ('tastopia', '0018_recipe_user'),
    ]

    operations = [
    ]
