# Generated by Django 4.1.7 on 2024-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0015_recipe_user'),
        ('tastopia', '0019_merge_0014_merge_20240519_0027_0018_recipe_user'),
    ]

    operations = [
    ]
