# Generated by Django 4.1.7 on 2024-05-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0020_merge_20240521_1459'),
        ('tastopia', '0020_merge_20240522_0024'),
    ]

    operations = [
    ]
