# Generated by Django 4.1.7 on 2024-05-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0021_merge_20240522_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='valorationCount',
            field=models.IntegerField(default=0),
        ),
    ]
