# Generated by Django 4.1.7 on 2024-05-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0022_recipe_valorationcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='valoration',
            field=models.FloatField(default=0.0),
        ),
    ]
