# Generated by Django 4.1.7 on 2024-05-23 07:14

from django.db import migrations, models
import tastopia.models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0023_alter_recipe_valoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=False, upload_to=tastopia.models.profileDirectoryPath),
            preserve_default=False,
        ),
    ]
