# Generated by Django 4.1.7 on 2024-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0024_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
