# Generated by Django 4.1.7 on 2024-05-23 08:00

from django.db import migrations, models
import tastopia.models


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0025_remove_comment_user_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=0, upload_to=tastopia.models.profileDirectoryPath),
            preserve_default=False,
        ),
    ]
