# Generated by Django 4.1.7 on 2024-05-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastopia', '0024_customuser_auth_alter_customuser_image'),
        ('tastopia', '0026_alter_customuser_image'),
    ]

    operations = [
    ]
